### PR TITLE
Fixed getting authoritive nameservers

### PR DESCRIPTION
**Pull request by affinityv**
Added function to properly get authoritative nameservers

### CODE REVIEW

**Comment by notthebee** [comment]
What's purpose of introducing different exit codes?

**Comment by affinityv** [comment]
> What's purpose of introducing different exit codes?

Well, if any part of the script fails, it can be referenced back to the exit code; a successful exit should always be 0.

**Comment by notthebee** [comment]
I get that, but I don't see the point of introducing different exit codes for different errors. The script is so simple that it would have no benefits – we don't have any use of the exit code after the script finished running.

**Comment by notthebee** [comment]
Thanks for the changes!

I've noticed that ${SUDO} is wrapped in double quotes in your verison of the script. It results in 'command not found errors', I removed the double quotes on my end, but they're still present in your version of the script (even though they don't show up in changes, weirdly enough).

**Comment by notthebee** [comment]
Just realized that it's probably because you didn't merge back my changes to the script

**Comment by affinityv** [comment]
> Thanks for the changes!
> 
> I've noticed that ${SUDO} is wrapped in double quotes in your verison of the script. It results in 'command not found errors', I removed the double quotes on my end, but they're still present in your version of the script (even though they don't show up in changes, weirdly enough).

Okay, otherwise all good?
I normally quote variables for safety, it often gives shellcheck errors when you don't.  Anyway, I removed the double quotes on SUDO and it checked out fine with shellcheck.  Let me know before I commit and push it back.

So... does it hurt to have the double quotes or not?  It was something else?

**Comment by notthebee** [comment]
Apart from ${SUDO} it seems to be fine – Having ${SUDO} wrapped in double quotes results in an error every time ${SUDO} is used.

**Comment by notthebee** [comment]
Rebase your branch against notthebee:testing please (only keep the authoritative nameservers function and the related stuff)

Also, have you tested it as follows?
1. Purposefully setting the DNS record wrong, and setting it correctly after the initial error message
2. Setting one of the subdomain DNS records wrong, and then setting it correctly after the initial error messag (repeat for both auth and wg)

The reason I ended up reverting to my initial solution is that the script wouldn't 'see' the changes made after the initial error, so if you changed the DNS record after getting the error, you'd have to re-run the entire script for it to 'see' your new DNS record.

**Comment by affinityv** [comment]
> Rebase your branch against notthebee:testing please (only keep the authoritative nameservers function and the related stuff)
> 
> Also, have you tested it as follows?
> 
>     1. Purposefully setting the DNS record wrong, and setting it correctly after the initial error message
> 
>     2. Setting one of the subdomain DNS records wrong, and then setting it correctly after the initial error messag (repeat for both auth and wg)
> 
> 
> The reason I ended up reverting to my initial solution is that the script wouldn't 'see' the changes made after the initial error, so if you changed the DNS record after getting the error, you'd have to re-run the entire script for it to 'see' your new DNS record.

Well.....
I think it would be better to define the target hostnames fully, I mean, what names will actually be needed?
Subdomains sometimes make sense and at other times they don't.  If a server is /just/ we web server, then www. subdomain /may/ be extra and unnecessary, but this gets off track.  So, what variants of the domain name in question are expected and/or required to match the same public IP address?

And another thing, don't forget that TTL is something that will effect your DNS query results, if you want to test with changing values, then you should use very low TTL values so that the server that responds to DNS queries will less likely give it's own cached answer, even if it is the authoritative server for the domain name.

Perhaps a per-requisite to using this project is to ensure that the correct domain names that will be targeted are already configured correctly for DNS.  It wouldn't hurt to do the checks, but you need to know exactly what is expected for the whole setup first.

Furthermore the "bootstrap" idea might be best limited to setting up the server to be ready to use ansible and that's it.  Then another script to test DNS and yet another script or two to populate the custom and secret files and then run the playbook(s).

An "all in one" script for everything up to optionally launching the playbook is fine, but it may benefit from an early option to "do all things" or start at a point and do further things from there or better still to act like the Debian text installer with options to step through the process -- you work through any steps that haven't been done yet and can come back and start [or any other step] at any point if you need to.  There is already a level of interactivity going on with this script anyway, so it's not like a "run this script and you are done".  Of course, it certainly is helpful to have all the steps as automated as possible via one or more scripts.

When it comes to manually editing custom.yml -- there should be a skeleton example file of the same showing everything that can and/or must be configured.

Setup / per-configure stage of the script (or it's own script), can query a custom.yml file, present it's current values and give the chance to update anything, list the contents and allow you to quit if done.

**Comment by notthebee** [comment]
> What variants of the domain name in question are expected and/or required to match the same public IP address?
Like I mentioned, domain.com, wg.domain.com and auth.domain.com

> Perhaps a pre-requisite to using this project is to ensure that the correct domain names that will be targeted are already configured correctly for DNS. It wouldn't hurt to do the checks, but you need to know exactly what is expected for the whole setup first.
I get that, but checking for errors early and warning the user about them is crucial for the UX of this script. Earlier versions of this script did not do any checks at all, and as a result, bunkerized-nginx would try to issue an SSL certificate again and again. And when the user would finally figure out what the issue was, Let's Encrypt would rate-limit the domain name, so the user would have to wait for a week to try again.

The decisions that I took while making this playbook come from trial, error and user testing. There's a reason why the domain checking is present, and it should stay in place – it works just fine for the purpose that it was made for.

> there should be a skeleton example file of the same showing everything that can and/or must be configured.
All the variables are present in vars.yml, and each one of them can be changed. This is also mentioned in the file. In my opinion, if the user skips the interactive script and wants to fill out the `custom.yml` file manually, they should understand that.

Splitting the script into several parts is not a good idea, in my opinion. It may be a more 'elegant' solution from a technical standpoint, but will ultimately bring no benefit to the user experience, at the same time introducing additional complexity into debugging, refactoring and testing. 

The changes that you have proposed to `bootstrap.sh` so far have been mostly aimed at making the code more "elegant", and I'm certainly thankful for your contributions. 

However, at the end of the day, it will be me who has to test, maintain and work on the script in the long run. And when it comes to it, I prefer code that is easier to read, debug and test to the code that is more elegant and correct. There are just some changes that I'm not going to be able to incorporate because of that, and I think you can see it in the changes that I've made to your refactor.

You're welcome to fork the script and restructure it the way you see fit, but I can't incorprorate the changes you propose to the upstream, unfortunately.

**Comment by affinityv** [comment]
> vars.yml, and

Okay, by vars.yml --- you mean vars: section of inventory.yml ?

**Comment by affinityv** [comment]
The double read statements are awkward; assigning a variable to empty, checking that it meets the requirements and that the variable has a value to check before throwing an error is more readable.

**Comment by affinityv** [comment]
Aside from the unusual "${SUDO}" issue, which seems odd to me, the quoting of variables is recommended by shellcheck.

**Comment by notthebee** [comment]
> > vars.yml, and
> 
> Okay, by vars.yml --- you mean vars: section of inventory.yml ?

Yes, sorry, that’s what I meant 



> The double read statements are awkward; assigning a variable to empty, checking that it meets the requirements and that the variable has a value to check before throwing an error is more readable.

True, but the initial version of your PR only checked if the variable is not empty. This resulted in e.g. smtp_host variable not being read at all, since the empty value after initialization already satisfies the regex. Though i later fixed that by replacing * in regex with +. 

There was also once case where the error was displayed before user input, but I don’t remember the exact place 

In general, `read`ing variables twice lets us display a different message in case of the error, not just if the value entered is empty

**Comment by notthebee** [comment]
> Aside from the unusual "${SUDO}" issue, which seems odd to me, the quoting of variables is recommended by shellcheck.

That is pretty weird, I agree. But in my case, wrapping sudo in quotes resulted in a `command not found` error whenever sudo was used

**Comment by affinityv** [comment]
Similar double work is happening in your "check_domain_dns" function; similar to the double "read" statements.

The following doesn't use the authoritative nameserver, but it fixes other issues with the checks.

How about this code:
```
check_domain_dns() {
	declare -a ip_array
	public_ip=$(curl -s ipinfo.io/ip)

	# Declare a hash map with subdomains and their respective IPs
	declare -A DOMAINS=(
		["root"]="$root_ip"
		["wg"]="$wg_ip"
		["auth"]="$auth_ip"
	)

	# Iterate through the subdomain hashmap until all of them resolve to the IP of the server
	FAILED_CHECK=0
	for domain in "${!DOMAINS[@]}"; do
		while :
		do
			if [[ $domain == "root" ]]; then
				work_domain="${root_host}"
			else
				work_domain="${domain}.${root_host}"
			fi
			# Get IPv4 address(es) from DNS query
			# - this may return more than one IPv4 address
			# - it will also remove CNAME data (if any)
			DOMAINS[${domain}]=$(
				dig +short @"${DNS}" \
					"${work_domain}" |
					grep '[1-9]*\.[0-9]*\.[0-9]*\.[0-9]*'|tr '\n' ' '
			)
			# The public ipv4 address must be found in the set returned
			# - NB: matching must be a full exact match
			ip_array=( ${DOMAINS[${domain}]} )
			declare -p ip_array|grep -q  "\"${public_ip}\""
			[[ $? == 0 ]] && { echo "${work_domain}: Ok"; break; }
			echo
			echo "The domain ${work_domain} does not resolve to the public IP of this server (${public_ip})"
			echo
			FAILED_CHECK=1;break
		done
		[[ ${FAILED_CHECK} -eq 1 ]] && break
	done
}

while :
do
	check_domain_dns
	[[ ${FAILED_CHECK} -eq 0 ]] && break
	root_host_prev="${root_host}"
	read -r -p "Domain name [${root_host_prev}]: " root_host
	[[ -z ${root_host} ]] && root_host="${root_host_prev}"
done
```

And this was a test script that I used:
[microsoft.com hard coded as first domain, gave it a0.affinityiq.net.au for testing]
Played around with IP addresses as needed for testing
NB: the 20.53.203.5 would have matched for 20.53.203.50 using "=~" ....

```
#!/bin/bash

DNS="1.1.1.1"
root_host="microsoft.com"

# test array created with dig against microsoft.com for IPv4 addresses
#declare -a ip_array=([0]="20.103.85.33" [1]="20.112.52.29" [2]="20.84.181.62" [3]="20.81.111.85" [4]="20.53.203.50")

check_domain_dns() {
	declare -a ip_array
	public_ip=$(curl -s ipinfo.io/ip)
	public_ip=20.53.203.5  # not valid, but would match =~
	public_ip=20.53.203.50 # valid
	public_ip=115.70.189.146

	# Declare a hash map with subdomains and their respective IPs
	declare -A DOMAINS=(
		["root"]="$root_ip"
		["wg"]="$wg_ip"
		["auth"]="$auth_ip"
	)

	# Iterate through the subdomain hashmap until all of them resolve to the IP of the server
	FAILED_CHECK=0
	for domain in "${!DOMAINS[@]}"; do
		while :
		do
			if [[ $domain == "root" ]]; then
				work_domain="${root_host}"
			else
				work_domain="${domain}.${root_host}"
			fi
			# Get IPv4 address(es) from DNS query
			# - this may return more than one IPv4 address
			# - it will also remove CNAME data (if any)
			DOMAINS[${domain}]=$(
				dig +short @"${DNS}" \
					"${work_domain}" |
					grep '[1-9]*\.[0-9]*\.[0-9]*\.[0-9]*'|tr '\n' ' '
			)
			# The public ipv4 address must be found in the set returned
			# - NB: matching must be a full exact match
			ip_array=( ${DOMAINS[${domain}]} )
			declare -p ip_array|grep -q  "\"${public_ip}\""
			[[ $? == 0 ]] && { echo "${work_domain}: Ok"; break; }
			echo
			echo "The domain ${work_domain} does not resolve to the public IP of this server (${public_ip})"
			echo
			FAILED_CHECK=1;break
		done
		[[ ${FAILED_CHECK} -eq 1 ]] && break
	done
}

while :
do
	check_domain_dns
	[[ ${FAILED_CHECK} -eq 0 ]] && break
	root_host_prev="${root_host}"
	read -r -p "Domain name [${root_host_prev}]: " root_host
	[[ -z ${root_host} ]] && root_host="${root_host_prev}"
done

exit 0
```

Result of test, using mircosoft.com -- then changing the domain to a0.affinityiq.net.au

```
$ /home/andrewm/dns-test-script.sh

The domain microsoft.com does not resolve to the public IP of this server (115.70.189.146)

Domain name [microsoft.com]: a0.affinityiq.net.au
a0.affinityiq.net.au: Ok
wg.a0.affinityiq.net.au: Ok
auth.a0.affinityiq.net.au: Ok
```

**Comment by affinityv** [comment]
I've done a re-base as you wanted, but there are a few other differences aside from the above script variance.   Also fixed an error on the user_password check that you had .... a "-n" was used instead of "-z" to report an empty password.

I'll push my changes, then do a new pull request post the re-base.

**Comment by notthebee** [comment]
Thank you, I will test the changes and merge as soon as I can.

One question – what is the purpose of the function `check_domain_dns_other_not_used`?

**Comment by affinityv** [comment]
That not used function, not ready to cull it yet for me.  The other looks good.  Still wondering if there is enough value using the authoritative nameservers, but I think we should if we use anything other than what the system provides by default; that is, rather use proper server in place of 1.1.1.1 or any other ones like that... more from the horse's mouth, rather than via 3rd party caching and also not wanting to pump up big tech that is a problem in itself in terms of privacy, security and the Internet in general amongst other reasons.

**Comment by affinityv** [comment]
btw I think that the [[ ]] structure is much more readable, perhaps you just need to get used to it; it's very clean and very easy to follow.

**Comment by notthebee** [comment]
Agree about the nameservers, 1.1.1.1 or another hardcoded resolver should be the last resort, if nothing else works. 

As for the `if` syntax, I think the explicit `if` is more in line with other programming languages. `else` is also not required with this syntax. The way you do it looks cleaner, but I still prefer the traditional explicit syntax, as it is more readable.

**Comment by affinityv** [comment]
Bump....

**Comment by affinityv** [comment]
Bump!

**Pull request closed without merging**
