### PR TITLE
bootstrap.sh: set timezone and mention .env to exec playbook

### PR DESCRIPTION
**Pull request by flavio-fernandes**
~~bootstrap.sh: set timezone and mention .env to exec playbook~~
bootstrap.sh: remove timezone setting and mention .env to exec playbook

### CODE REVIEW

**Comment by flavio-fernandes** [comment]
@notthebee please take a look and see if this PR is useful.

PS. Thanks for the [youtube](https://youtu.be/SMF301vQqJo) on using this!

**Comment by notthebee** [comment]
The Python env should get activated automatically when you enter the folder (via direnv)

As for the timezone – that's actually a really good point, but I think what I'd do instead is remove the handling of the timezone altogether. There's no reason to change it in this playbook.

**Comment by flavio-fernandes** [comment]
> The Python env should get activated automatically when you enter the folder (via direnv)
> 

Interesting, but that is not what I observe. See below. Can you please try and see if that is working for you?

```
...
Success!
Would you like to run the playbook now? [y/N]:
You can run the playbook by executing the following command
cd /root/ansible-easy-vpn && source ./.venv/bin/activate && ansible-playbook run.yml
root@flaviof:~# exit
logout
Connection to ffdesivps.duckdns.org closed.
$
$ ssh root@ffdesivps.duckdns.org
root@ffdesivps.duckdns.org's password:
Welcome to Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-69-generic x86_64)
...
Last login: Sun Apr  2 23:54:55 2023
root@flaviof:~# which ansible-playbook
root@flaviof:~# which python
root@flaviof:~#
root@flaviof:~# cd /root/ansible-easy-vpn && source ./.venv/bin/activate
(.venv) root@flaviof:~/ansible-easy-vpn# which ansible-playbook
/root/ansible-easy-vpn/.venv/bin/ansible-playbook
(.venv) root@flaviof:~/ansible-easy-vpn# which python
/root/ansible-easy-vpn/.venv/bin/python
```

> As for the timezone – that's actually a really good point, but I think what I'd do instead is remove the handling of the timezone altogether. There's no reason to change it in this playbook.

Sounds good. I've removed the timezone bits from the PR. Please see if that looks better to you.

**Comment by notthebee** [comment]
So, I've finally managed to test things out :) 
The reason why the Python venv didn't kick in is due to incorrect instructions in the bootstrap.sh. So I've edited the instructions in the main branch to reflect that.

Please rebase against the current main and remove the bootstrap.sh. After that, I can merge the PR  😄

**Comment by flavio-fernandes** [comment]
oh, looks like you took care of it. Thanks!

**Pull request merged**
