### PR TITLE
Added Debian Support

### PR DESCRIPTION
**Pull request by GirishMahabir**
## Added Checks in bootstrap.sh
- Checks for Debian-based distro.
- Add true to iptables and false to ufw if on Debian.

### CODE REVIEW

**Comment by notthebee** [comment]
Is there any particular reason for replacing UFW with iptables? As far as I know, UFW can be installed on Debian

**Comment by GirishMahabir** [comment]
Hello,

Actually, Iptables is the default firewall for Debian, same as ufw for ubuntu, and installing ufw on top of it might cause conflicts.

That's why I prefer to just use the default.

Kind Regards,
Girish Mahabir

**Comment by notthebee** [comment]
I understand the motivation, but I would prefer if you didn’t change the essential functionality of the playbook. iptables is also present in Ubuntu and coexists with ufw with no problem.

**Comment by GirishMahabir** [comment]
Ok sure, Let me work on it a bit more to make it use ufw itself then.

Thanks @notthebee

**Comment by notthebee** [comment]
Are you still planning to work on it?

**Comment by GirishMahabir** [comment]
Yes, not in the next week tho, maybe after that

**Comment by affinityv** [comment]
Either way, it wouldn't hurt if both UFW and iptables were able to work and it was a choice.  That would be my vote.

**Comment by notthebee** [comment]
In my opinion, giving the user a choice between firewall implementations that doesn't have any meaningful impact on functionality is unnecessary. At the end, it just adds more maintenance overhead with no tangible benefits.

**Comment by affinityv** [comment]
Also, right now I'm happy enough to go with Ubuntu LTS, but my preference has been Devuan for some time now, which is based on Debian, but with choice over systemd.  What I care most about though is running an up to date and fully supported installations, which is why LTS might win out for me in the short term and to lessen worry for a number of years in terms of "easier" support.  Lots of solutions should, in my opinion, be as generic as possible to allow for choice of OS and OS installation options.

**Comment by notthebee** [comment]
While I agree with the general sentiment, supporting multiple operating systems impacts testing a lot. And since it's ultimately me who would have to maintain this project, I'd rather support one operating system well, than claim support for multiple and have to spend expontentilaly more time on testing

**Comment by affinityv** [comment]
> While I agree with the general sentiment, supporting multiple operating systems impacts testing a lot. And since it's ultimately me who would have to maintain this project, I'd rather support one operating system well, than claim support for multiple and have to spend expontentilaly more time on testing

Sure, but Debian based distros have a lot in common; so it might not be that hard; it's like being as standards compliant as possible, ala, best practice and not doing things like adding or using features that are very distro specific.

**Comment by notthebee** [comment]
Debian will still have different dependencies and different versions of packages in the repos, which might break stuff.

Currently the dependencies is the only thing that is Ubuntu-specific, but once again – just adding the support for Debian is half the battle. Maintaining, testing, and making sure it keeps working on Debian is more of a concern.

**Comment by notthebee** [comment]
Closing due to inactivity.

**Pull request closed without merging**
